GET http://localhost:3000/api/getDatabaseId?database=posts

### 

GET http://localhost:3000/api/posts

### 

GET http://localhost:3000/api/post?slug=querobolin

###

GET http://localhost:3000/api/config